### PR TITLE
fixed #50

### LINKED ISSUE #50: Broken links in MC
- Entry page, the link for “How do I find my password” does not go to an existing Wiki page.
- In MC/settings, links next to: 
     - Application Insights (I get “error retrieving data”)
     - ASA policy evaluation (I get “This asset was not found, it may have been deleted”)
     - ASA join server (I get “This asset was not found, it may have been deleted”)

### PR DESCRIPTION
**Pull request by lhoang29**

### CODE REVIEW

File: mc/Controllers/HomeController.cs [hunk 1]
```diff
@@ -415,10 +415,10 @@ private List<SettingItemViewModel> SettingsView()
...
+                new { Name = nameof(svm.ASAJoinName), Tooltip = "View ASA Join Query", Url = $"https://ms.portal.azure.com/#resource/subscriptions/{svm.AzureSubscriptionId}/resourceGroups/{svm.AzureResourceGroupName}/providers/Microsoft.StreamAnalytics/streamingjobs/{svm.ASAJoinName}/overview"},
+                new { Name = nameof(svm.ASAEvalName), Tooltip = "View ASA Policy Evaluation Query", Url = $"https://ms.portal.azure.com/#resource/subscriptions/{svm.AzureSubscriptionId}/resourceGroups/{svm.AzureResourceGroupName}/providers/Microsoft.StreamAnalytics/streamingjobs/{svm.ASAEvalName}/overview"},
+                new { Name = nameof(svm.OnlineTrainerAddress), Tooltip = "Configure Online Trainer", Url = $"https://ms.portal.azure.com/#resource/subscriptions/{svm.AzureSubscriptionId}/resourceGroups/{svm.AzureResourceGroupName}/providers/Microsoft.ClassicCompute/domainNames/trainer-{uniqueStringInUrl}/overview"}
```
Comment (eisber) [inline mc/Controllers/HomeController.cs]: can you centralize the "trainer-" prefix? Ideally {svm.TrainerId}

Comment (lhoang29) [inline mc/Controllers/HomeController.cs]: good point, I'm parsing the online trainer URL now to get the Id

**Comment by lhoang29** [comment]
@eisber can you review additional changes?
